#pragma once

#include <unordered_map>
#include <set>

enum class LocationID
{
    NONE,
    CHIKA_RESCUE = 1,
    KANAN_RESCUE,
    DIA_RESCUE,
    RUBY_RESCUE,
    YOU_RESCUE,
    MARI_RESCUE,
    RIKO_RESCUE,
    HANAMARU_RESCUE,

    CHIKA_UPGRADE_QUEST = 20,
    RIKO_UPGRADE_QUEST,
    KANAN_UPGRADE_QUEST,
    HANAMARU_UPGRADE_QUEST,
    RUBY_UPGRADE_QUEST,
    YOU_UPGRADE_QUEST,
    DIA_UPGRADE_QUEST,
    MARI_UPGRADE_QUEST,

    SUNKEN_TEMPLE_BOSS = 40,
    RUINS_BOSS_1,
    RUINS_BOSS_2,
    RUINS_BOSS_3,
    GROTTO_BOSS,
    CORAL_HILL_BOSS,
    SEA_OF_TREES_BOSS,
    CRYSTALLINE_GROTTO_BOSS,
    SUNKEN_VOLCANO_BOSS,
    SHIPWRECK_BOSS,
    INFERNAL_ALTAR_BOSS,

    SUNKEN_TEMPLE_BOSS_REFIGHT = 60,
    RUINS_BOSS_REFIGHT,
    GROTTO_BOSS_REFIGHT,
    CORAL_HILL_BOSS_REFIGHT,
    SEA_OF_TREES_BOSS_REFIGHT,
    CRYSTALLINE_GROTTO_BOSS_REFIGHT,
    SUNKEN_VOLCANO_BOSS_REFIGHT,
    SHIPWRECK_BOSS_REFIGHT,
    INFERNAL_ALTAR_BOSS_REFIGHT,

    SUNKEN_TEMPLE_CAST_TUTORIAL_LEFT_CHEST = 80, // 1, 1
    SUNKEN_TEMPLE_CAST_TUTORIAL_RIGHT_CHEST, // 1, 2
    SUNKEN_TEMPLE_FISHY_ARCHERY_CHEST, // 1, 5
    SUNKEN_TEMPLE_PATHWAY_TO_INFERNAL_ALTAR_CHEST, // 1, 6
    SUNKEN_TEMPLE_KATYS_MASK_CHEST, // 1, 3
    SUNKEN_TEMPLE_CHIKA_TESTING_GROUNDS_CHEST, // 1, 4
    GROTTO_FIRST_SAVE_ROOM_CHEST, // 3, 11
    GROTTO_FIRST_WATTERFALL_CHEST, // 3, 5
    GROTTO_FIRST_LAKE_CHEST, // 3, 10
    GROTTO_SECOND_LAKE_CHEST, // 3, 12
    GROTTO_SPELLBOOK_CHEST, // 3, 4
    GROTTO_LONG_WATTERFALL_CHEST, // 3, 3
    GROTTO_ISOLATED_CLIMB_CHEST, // 3, 2
    GROTTO_CAVE_CLIMB_CHEST, // 3, 1
    RUINS_SANDY_TRAP_CHEST, // 2, 3
    RUINS_VERTICAL_POISON_CHEST, // 2, 5
    RUINS_ROLLING_ROCKS_CHEST, // 2, 4
    RUINS_LAPTOP_CHEST, // 2, 1
    RUINS_HALL_OF_SHAME_CHEST, // 2, 2
    SUNKEN_VOLCANO_FIRST_SAVE_ROOM_CHEST, // 7, 17
    SUNKEN_VOLCANO_HOTSPRING_CHEST, // 7, 18
    SUNKEN_VOLCANO_SOARSHOES_CHEST, // 7, 14
    SUNKEN_VOLCANO_SOARSHOES_OBLIGATORY_CHEST, // 7, 16
    SUNKEN_VOLCANO_TONOSAMA_PARTS_CHEST, // 7, 15
    SHIPWRECK_SEALED_OFF_CHEST, // 8, 7
    SHIPWRECK_SPIKEY_BALL_FISH_CHEST, // 8, 8
    SHIPWRECK_FINAL_GUARD_CHEST, // 8, 4
    SHIPWRECK_GLOVES_OF_MIGHT_CHEST, // 8, 3
    SHIPWRECK_POSTAL_GUILD_BAG_CHEST, // 8, 2
    CORAL_HILL_SHOARSHOESNT_CHEST, // 4, 3
    CORAL_HILL_TELEPORTING_FISH_CHEST, // 4, 8
    CORAL_HILL_WALLCRAB_CHEST, // 4, 7
    CORAL_HILL_CHIKA_BLOCK_CHEST, // 4, 4
    CORAL_HILL_LOST_MONSTIE_CHEST, // 4, 1
    CRYSTALLINE_GROTTO_ONE_WAY_SLIDE_CHEST, // 6, 1
    CRYSTALLINE_GROTTO_GIANT_CRYSTAL_CHEST, // 6, 2
    CRYSTALLINE_GROTTO_ISOLATED_CHEST, // 6, 4
    CRYSTALLINE_GROTTO_CUTE_POCHETTE_CHEST, // 6, 5
    CRYSTALLINE_GROTTO_MARI_ISSUE_CHEST, // 6, 3
    SEA_OF_TREES_POISON_CRAB_CHEST, // 5, 2
    SEA_OF_TREES_SCARLET_DELTA_SUIT_CHEST, // 5, 3
    SEA_OF_TREES_GOLDEN_SNAIL_CHEST, // 5, 6
    SEA_OF_TREES_SLOPE_ROOM_CHEST, // 5, 4
    SEA_OF_TREES_YOU_TESTING_GROUNDS_CHEST, // 5, 7
    INFERNAL_ALTAR_PURPLE_GOO_CHEST, // 9, 2
    INFERNAL_ALTAR_DARK_ROOM_CHEST, // 9, 1
    CHEST_ID_MAX = INFERNAL_ALTAR_DARK_ROOM_CHEST,

    RECIPE_01 = 701,
    RECIPE_02,
    RECIPE_03,
    RECIPE_04,
    RECIPE_05,
    RECIPE_06,
    RECIPE_07,
    RECIPE_08,
    RECIPE_09,
    RECIPE_10,
    RECIPE_11,
    RECIPE_12,
    RECIPE_13,
    RECIPE_14,
    RECIPE_15,
    RECIPE_16,
    RECIPE_17,
    RECIPE_18,
    RECIPE_19,
    RECIPE_20,
    RECIPE_21,
    RECIPE_22,
    RECIPE_23,
    RECIPE_24,
    RECIPE_25,
    RECIPE_26,
    RECIPE_27,
    RECIPE_28,
    RECIPE_29,
    RECIPE_30,
    RECIPE_31,
    RECIPE_32,
    RECIPE_33,
    RECIPE_34,
    RECIPE_35,
    RECIPE_36,
    RECIPE_37,
    RECIPE_38,
    RECIPE_39,
    RECIPE_40,
    RECIPE_41,
    RECIPE_42,
    RECIPE_43,
    RECIPE_44,
    RECIPE_45,
    RECIPE_46,
    RECIPE_47,
    RECIPE_48,
    RECIPE_49,
    RECIPE_50,
    RECIPE_51,
    RECIPE_52,
    RECIPE_53,
    RECIPE_54,
    RECIPE_55,
    RECIPE_56,
    RECIPE_57,
    RECIPE_58,
    RECIPE_59,
    RECIPE_60,
    RECIPE_61,
    RECIPE_62,
    RECIPE_63,
    RECIPE_64,
    RECIPE_65,
    RECIPE_66,
    RECIPE_67,
    RECIPE_68,
    RECIPE_69,
    RECIPE_70,
    RECIPE_71,
    RECIPE_72,
    RECIPE_73,
    RECIPE_74,
    RECIPE_75,
    RECIPE_76,
    RECIPE_77,
    RECIPE_78,
    RECIPE_79,
    RECIPE_80,
    RECIPE_81,
    RECIPE_82,
    RECIPE_83,
    RECIPE_84,
    RECIPE_85,
    RECIPE_86,
    RECIPE_87,
    RECIPE_88,
    RECIPE_89,
    RECIPE_90,
    RECIPE_91,
    RECIPE_92,
    RECIPE_93,
};

class LocationManager
{
private:
    LocationManager() {};

public:
    static LocationManager& getInstance()
    {
        static LocationManager instance;
        return instance;
    }

    LocationManager(LocationManager const&) = delete;
    void operator=(LocationManager const&) = delete;

    void Init(const char* path);
    void OnConnect();
    void OnFrame(double delta);

    void OnLocationChecked(int64_t location_id);

    std::set<int64_t> GetActiveLocations();

private:
    void OnFrameCheckChests();
    void OnFrameCheckBosses();
    void OnFrameCheckRescues();
    void OnFrameCheckQuests();
    void OnFrameCheckRecipes();
};
